HOUSE_THEMES = {
    1: {
        "title": "1st House — Identity / Selfhood",
        "theme": "“I exist”",
        "nn": "Independence, personal initiative, the courage to be yourself, and reliance on your own decisions.",
        "sn": "Living through partners, depending on others’ opinions, dissolving yourself in relationships.",
        "key": "from “we” → to “I”",
    },
    2: {
        "title": "2nd House — Values / Resources",
        "theme": "“What is mine and what I can rely on”",
        "nn": "Self-worth, financial stability, simple joys, the ability to earn and preserve resources.",
        "sn": "Living in crises, dependence on others’ resources, emotional/financial entanglement.",
        "key": "from dependence → to stability",
    },
    3: {
        "title": "3rd House — Communication / Learning",
        "theme": "“How I think and communicate”",
        "nn": "Dialogue, learning, curiosity, the ability to explain and truly listen.",
        "sn": "Living in abstract truths, “I know how it should be”, escaping into theory.",
        "key": "from ideology → to living dialogue",
    },
    4: {
        "title": "4th House — Home / Roots / Inner World",
        "theme": "“Where my inner support lies”",
        "nn": "Contact with feelings, personal inner space, emotional safety, care for self and close ones.",
        "sn": "Living only through outer status, depending on recognition, ignoring inner needs.",
        "key": "from external success → to inner foundation",
    },
    5: {
        "title": "5th House — Self-Expression / Creativity",
        "theme": "“What makes me feel alive”",
        "nn": "Joy, creativity, play, personal expression, connection with the heart.",
        "sn": "Dissolving into groups, living by collective interests, being a function rather than a person.",
        "key": "from the group → to the heart",
    },
    6: {
        "title": "6th House — Work / Skills / Service",
        "theme": "“How I am useful to the world”",
        "nn": "Discipline, skills, care for the body, practicality, steady work.",
        "sn": "Escaping reality, self-sacrifice, chaos, avoiding responsibilities.",
        "key": "from dissolution → to meaningful action",
    },
    7: {
        "title": "7th House — Relationships / Partnership",
        "theme": "“How I relate to others”",
        "nn": "Partnership, cooperation, hearing the other, balancing interests.",
        "sn": "Isolation, “I do it alone”, constant fight for autonomy.",
        "key": "from a solitary path → to dialogue",
    },
    8: {
        "title": "8th House — Transformation / Depth",
        "theme": "“Crises and rebirth”",
        "nn": "Trust, intimacy, working with crises, psychological depth.",
        "sn": "Fixation on comfort, fear of loss, excessive control.",
        "key": "from stability → to depth",
    },
    9: {
        "title": "9th House — Meaning / Worldview",
        "theme": "“Why I live”",
        "nn": "Philosophy, faith, search for meaning, learning through experience, expansion of horizons.",
        "sn": "Triviality, constant busyness, fragmented information.",
        "key": "from facts → to meaning",
    },
    10: {
        "title": "10th House — Direction / Vocation",
        "theme": "“Who I am becoming in the world”",
        "nn": "Responsibility, long-term goals, structure, visible realization.",
        "sn": "Attachment to the past, dependence on family comfort, fear of stepping into the public world.",
        "key": "from comfort → to realization",
    },
    11: {
        "title": "11th House — Community / Mission",
        "theme": "“My contribution to the collective”",
        "nn": "Teamwork, social mission, future-oriented thinking, participation in communities.",
        "sn": "Egocentrism, focus only on oneself, needing a personal stage.",
        "key": "from “me” → to “we”",
    },
    12: {
        "title": "12th House — Letting Go / Inner Silence",
        "theme": "“Connection to something greater”",
        "nn": "Acceptance, trust in life, compassion, inner silence, service without ego.",
        "sn": "Workaholism, control, being trapped in routine.",
        "key": "from control → to trust",
    },
}
# NodAL SIGN AXES: key is NORTH sign (because we interpret growth direction)
SIGN_AXES = {
    "Aries": {
        "north_title": "North Node in Aries — qualities to develop",
        "north": "Independence, initiative, courage, the right to want your own.",
        "south_title": "South Node in Libra — habitual pattern",
        "south": "Adapting, avoiding conflict, living through others’ expectations.",
        "bridge": "From pleasing others → to initiating your own path.",
        "motto": "Allow yourself to be first.",
    },
    "Taurus": {
        "north_title": "North Node in Taurus — qualities to develop",
        "north": "Stability, simplicity, embodiment, sustainable growth.",
        "south_title": "South Node in Scorpio — habitual pattern",
        "south": "Intensity, crises, dramatization, digging too deep.",
        "bridge": "From surviving the storm → to building calm ground.",
        "motto": "Live, don’t just survive.",
    },
    "Gemini": {
        "north_title": "North Node in Gemini — qualities to develop",
        "north": "Listening, clarifying, asking questions, dialogue as equals.",
        "south_title": "South Node in Sagittarius — habitual pattern",
        "south": "Certainty, teaching, abstract ‘big truths’ over details.",
        "bridge": "From “I know the truth” → to dialogue.",
        "motto": "Truth is born in dialogue.",
    },
    "Cancer": {
        "north_title": "North Node in Cancer — qualities to develop",
        "north": "Emotional closeness, care, vulnerability, contact with feelings.",
        "south_title": "South Node in Capricorn — habitual pattern",
        "south": "Duty-first living, emotional suppression, rigid strength.",
        "bridge": "From rigidity → to feeling.",
        "motto": "Let yourself be alive.",
    },
    "Leo": {
        "north_title": "North Node in Leo — qualities to develop",
        "north": "Personal expression, joy, creativity, leading with the heart.",
        "south_title": "South Node in Aquarius — habitual pattern",
        "south": "Distance, living in ideas, observing rather than feeling.",
        "bridge": "From detachment → to the heart.",
        "motto": "Not only think — feel.",
    },
    "Virgo": {
        "north_title": "North Node in Virgo — qualities to develop",
        "north": "Discipline, usefulness, concrete skills, service through action.",
        "south_title": "South Node in Pisces — habitual pattern",
        "south": "Drifting, lack of structure, self-sacrifice, avoidance.",
        "bridge": "From dissolution → to form.",
        "motto": "Spirituality through practice.",
    },
    "Libra": {
        "north_title": "North Node in Libra — qualities to develop",
        "north": "Cooperation, diplomacy, hearing the other, partnership-based decisions.",
        "south_title": "South Node in Aries — habitual pattern",
        "south": "Solo action, competition, direct confrontation.",
        "bridge": "From “I act alone” → to “we act together”.",
        "motto": "Negotiate, don’t conquer.",
    },
    "Scorpio": {
        "north_title": "North Node in Scorpio — qualities to develop",
        "north": "Depth, transformation, courage to change, trust in the process.",
        "south_title": "South Node in Taurus — habitual pattern",
        "south": "Clinging to comfort, avoiding change, material safety-first.",
        "bridge": "From comfort → to transformation.",
        "motto": "Growth begins where control ends.",
    },
    "Sagittarius": {
        "north_title": "North Node in Sagittarius — qualities to develop",
        "north": "Meaning, worldview, long-term direction, learning through lived experience.",
        "south_title": "South Node in Gemini — habitual pattern",
        "south": "Collecting facts, switching constantly, knowing a bit of everything.",
        "bridge": "From information → to meaning.",
        "motto": "Don’t just know — understand.",
    },
    "Capricorn": {
        "north_title": "North Node in Capricorn — qualities to develop",
        "north": "Maturity, responsibility, inner authority, long-term direction.",
        "south_title": "South Node in Cancer — habitual pattern",
        "south": "Seeking safety, relying on the past, emotional dependence.",
        "bridge": "From safety → to responsibility.",
        "motto": "Build the future on purpose.",
    },
    "Aquarius": {
        "north_title": "North Node in Aquarius — qualities to develop",
        "north": "Teamwork, contribution, future-oriented thinking, social usefulness.",
        "south_title": "South Node in Leo — habitual pattern",
        "south": "Needing recognition, personal spotlight, ego-driven expression.",
        "bridge": "From personal spotlight → to shared purpose.",
        "motto": "Be unique — for the collective.",
    },
    "Pisces": {
        "north_title": "North Node in Pisces — qualities to develop",
        "north": "Trust, acceptance, compassion, letting go of perfect control.",
        "south_title": "South Node in Virgo — habitual pattern",
        "south": "Over-analysis, perfectionism, controlling every step.",
        "bridge": "From control → to trust.",
        "motto": "Not everything can be calculated.",
    },
}